image: node:19.6.0 

default:
  tags:
    - node

stages:
  - setup
  - build

dependencies_install:
  stage: setup
  image: node:19.6.0 
  tags:
    - docker
  script:
    - echo "starting dependencies install"
    - npm install -g @angular/cli@latest
    - npm install --force
    - echo "Staring npm build"
    - npm run build

build_image:
  stage: build
  image: docker:23.0.5
  services:
    - docker:23.0.5-dind
  variables:
    IMAGE_NAME: juliawakaba/pms-naiparq-frontend
    IMAGE_TAG: latest
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PWD
  script:
    - echo "Push to docker hub" 
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG