stages:
  - setup
  - build

dependencies_install:
  stage: setup
  image: node:19.6.0 
  tags:
    - docker
  script:
    - npm install -g @angular/cli@latest
    - npm install --force
    - npm run build

build_image:
  stage: build
  image: docker:23.0.5
  services:
    - docker:23.0.5-dind
  variables:
    - IMAGE_NAME: juliawakaba/pms-naiparq-frontend:
    - IMAGE_TAG: latest
    - DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PWD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG