image: node:19.6.0 

variables:
  GIT_DEPTH: 0

default:
  tags:
    - node
    - docker

stages:
  - setup
  - build
  - docker_push
  - publish

install_dependencies:
  stage: setup
  script:
    - echo "starting dependencies install"
    - npm install --force
  only:
    - develop
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules


build_frontend_image:
  stage: build
  script:
    - echo "Staring npm build"
    - npm run build
  artifacts:
    paths:
      - dist/
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
    policy: pull


push-docker-registry:
  stage: docker_push
  image: docker:23.0.5
  services:
    - docker:dind
  variables:
    IMAGE_NAME: juliawakaba/pms-naiparq-frontend
    IMAGE_TAG: latest
    # DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PWD
  script:
    - echo "Push to docker hub" 
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG


deploy_to_production_server:
  stage: publish
  image: docker:23.0.5
  services:
    - docker:dind
  variables:
    IMAGE_NAME: juliawakaba/pms-naiparq-frontend
    IMAGE_TAG: latest
    # PWD: "#B9cC7"
  before_script:
    - apk add --update --no-cache openssh-client sshpass
    - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
    - sshpass -p $SERVER_PWD ssh-copy-id -o StrictHostKeyChecking=no -p 999 root@104.238.161.77
    - docker login -u $DOCKER_USER -p $DOCKER_PWD
  script:
    - sshpass -p $SERVER_PWD ssh -p 999 -o StrictHostKeyChecking=no root@104.238.161.77 "cd /home/naiparq/naiparq-pms-frontend && docker system prune -af && docker run --rm -v pms_web_portal:/data/ ubuntu /bin/sh -c 'rm -rf /data/*' && docker pull $IMAGE_NAME:$IMAGE_TAG && docker run -d --name frontend_prod -v pms_web_portal:/var/www/html/ $IMAGE_NAME:$IMAGE_TAG && docker system prune -af"

























    
    
    # - sshpass -p "#B9cC7(WANcE=mNo" scp -o StrictHostKeyChecking=no  root@104.238.161.77:/home/naiparq/naiparq-pms-frontend/
    # - sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no -r site/* $USERNAME@$HOST:/var/www/html/
    # - docker system prune -af
    # - echo "Pull from docker hub" 
    # - docker run --rm -v pms_web_portal:/data/ ubuntu /bin/sh -c "rm -rf /data/*"
    # - docker pull $IMAGE_NAME:$IMAGE_TAG
    # - docker run -d --name frontend_prod -v pms_web_portal:/var/www/html/ $IMAGE_NAME:$IMAGE_TAG
    # - docker system prune -af
